global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'trading_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'market_price_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: 'config_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']

  - job_name: 'transfer_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
